### ISSUE TITLE
Incorporate into Biopython

### ISSUE THREAD

**Issue by rchurt** [glarue/jgi-query#12]
Love the idea of this tool--what would you think of making it a package in Biopython so users could just do `from Bio import jgi-query`, or even making it a single function in Biopython? I don't know anything about how you would do this, but I'm sure the folks over there would be happy to help, and I think it would make it even easier to deploy and use.

**Comment by glarue** [comment]
Hey @rchurt, thanks for the idea. I wonder, though, how frequent of a use-case this would be (accessing it programmatically from within Python vs. via CLI)—do you have any examples of how you're thinking that might be of use? The way I've always used it is for pulling JGI files onto remote servers where I don't have any web-based interface options, but I'm curious to hear if you've encountered specific cases where having direct programmatic access would be helpful.

One thing I certainly plan to do at some point is package everything up to be `pip`-installable in order to make installation as painless as possible (though, since it's currently just a single Python script, "installation" is really just putting the script somewhere convenient).

**Comment by rchurt** [comment]
So I was imagining using it exactly like I use Biopython's [`Bio.Entrez`](https://biopython.org/docs/1.75/api/Bio.Entrez.html) package for batch retrieving records that happen to only be available on the JGI genome portal (otherwise I would just get them from NCBI). I'd assumed that was what everyone was doing with this script, but you'd know better than me!

**Comment by glarue** [comment]
Gotcha, right—I don't use `Entrez` very much, but I can see how there are possible applications there as they both involve querying sequence databases.

I'm not too informed about how `Bio.Entrez` pulls its data, or whether NCBI has a more advanced API to handle things like file streaming (e.g. `.read()`), etc. JGI's API is fairly anemic in that they really only provide a way to download an XML. Most of what `jgi-query` does is simply parse that XML and present it more (arguably) accessibly.

Regardless, I think it's a great idea but suspect it would involve essentially a complete re-write of the code. I'd certainly welcome anyone with the Python chops to use as much of my codebase as they see fit, but I doubt I will have time to dedicate to doing it myself in the near/medium future.
