### ISSUE TITLE
Downloading the fungal database

### ISSUE THREAD

**Issue by abdeljalil-senhaji** [glarue/jgi-query#15]
Hello,
I wanted to download the entire fungal database, but the tool is not responding. Do you have any solution to recommend ?
It takes a lot of time and in the end it gives me an empty XML file.
Thanks in advance.

ERROR :
#-------------------------------------------------------------------------------------------
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    92    0    92    0     0      0      0 --:--:--  0:10:00 --:--:--    22
Retrieving information from JGI for query 'fungi' using command 'curl 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=fungi' -L -b cookies > fungi_jgi_index.xml'


Traceback (most recent call last):
  File "/shared/ifbstor1/projects/HE/FungiDB/JGI-db/jgi-query-main/jgi-query.py", line 1151, in <module>
    if not any(v["results"] for v in list(file_list.values())):
AttributeError: 'NoneType' object has no attribute 'values'
```
#--------------------------------------------------------------------------------------------

FILE XML :  fungi_jgi_index.xml

```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

**Comment by glarue** [comment]
Hi @abdeljalil-senhaji, sorry for the trouble!

From what I can tell, this is some combination of a caching timeout issue on JGI's end and/or a reformat of their data architecture. The specific error you're seeing is due to the fact that no results are being retrieved.

First, I've tested some single-organism commands and confirmed that the basic functionality of `jgi-query` is working (e.g., `jgi-query.py Nemve1` works as expected).

Second, I get the same error as you when running with `fungi` as the query. The last time I tested this query was a number of years ago at this point, and their database has likely grown substantially since then, which may make downloading the entire index unfeasible. Using the query `fungi` was never actually documented on the JGI side, and I was initially surprised it worked at all. Something else that sometimes happens is that the initial download fails due to slow backend caching, but that a subsequent request will work. That, for example, happened to me during testing just now with the query `1000_fungi_project`. Initially, it failed with an error about the file not being present, but a subsequent request successfully fetched the (very long) index file.

The best thing I can suggest is to try a few `fungi` requests in a row separated by ~5-10 minutes. Beyond that, you could try the `1000_fungi_project` query depending on your needs. It's arduous, but one way to identify potential supersets of data that are compatible with the API `jgi-query` uses is by searching [here](https://genome.jgi.doe.gov/portal/), and following the `Download` link from the `Resources` column to get the `organism=` tag from the resulting URL, which you can feed to `jgi-query` as the query string.

**Comment by abdeljalil-senhaji** [comment]
Hello @glarue,

Thank you for your response, it really helped me to think.
I managed to recover the Fungal database in the end.
I am leaving the instructions here to help anyone in need.

Before launching the [jgi-query.py](https://github.com/glarue/jgi-query/blob/main/jgi-query.py), I downloaded the index files using the following command:
`curl 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=fungi' -L -b ../cookies > fungi_jgi_index.xml `
Then, I ran the script by specifying the index file:
`python3 ../jgi-query.py -x fungi_jgi_index.xml`

:)

**Comment by glarue** [comment]
@abdeljalil-senhaji I'm glad it worked out! I'm curious whether you tried without the `-L` flag first. If not and you're willing to try again, it'd be interesting to see if it succeeds that way too. If so, it suggests perhaps it was simply a backend issue (because `jgi-query` uses the same `curl` command internally, so one imagines it should work there as well). Definitely keep that index file around for future use!
