### ISSUE TITLE
failed when using jgi-query to download files wanted

### ISSUE THREAD

**Issue by liupfskygre** [glarue/jgi-query#5]
Hi Glarue,
    I am trying to using the following command to download the files in the projects, but I get an error message and the file with the right name but wrong content:

## command:
python jgi-query.py -x get-directory.xml # the xml file is downloaded from the project download page

#https://genome.jgi.doe.gov/portal/pages/dynamicOrganismDownload.jsf?organism=TheHunmicrobiome# 

by click 'Open Downloads as XML ' 

# following the instructions:
user name and password #fine 

# file to download
# for example
2:2216 # a protein seqs file I want download

# I got this
Total download size of selected files: 693.23 KB
Continue? (y/n): y
Downloading '81031.assembled.faa' using command:
curl http://genome.jgi.doe.gov/EubpyrIsolGenome/download/_JAMO/56f1982d7ded5e7f7b938de5/81031.assembled.faa -b cookies -c cookies -L > 81031.assembled.faa
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   287  100   287    0     0    101      0  0:00:02  0:00:02 --:--:--   101
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100  9122    0  9122    0     0   2240      0 --:--:--  0:00:04 --:--:--  2240
Finished downloading all files.
ERROR: '81031.assembled.faa' appears to be malformed and will be left unmodified.
Keep temporary files ('/home/mpi/pengfei/Hungate1000p/get-directory.xml' and 'cookies')? (y/n): n
Removing temp files and exiting

# and the file is wrong: not protein sequences, see attached
[81031.assembled.faa.txt](https://github.com/glarue/jgi-query/files/1872925/81031.assembled.faa.txt)

would you please help checking which step I am doing wrong?
Thanks

Best,
Pengfei

**Comment by glarue** [comment]
Hi Pengfei,

The error you are getting is not because you are running `jgi-query` incorrectly. Rather, it is due to the way JGI stores certain files in their database.

Sometimes (and I am not entirely clear on the details here), files stored in tape archives on JGI are not properly triggered for retrieval by cURL, and `jgi-query` simply gets an error XML file instead.

There is a (annoying) way to fix this; you can use the web interface to force JGI to activate the archive manually:

1. Open the file hierarchy via a web browser
2. Find the file you wish to download
3. Click on the file name via the browser; this should produce a message from JGI: "Checking tape transfer status"
4. Wait (possibly for quite a while)
5. Once the file download dialog box pops up in your browser, cancel it and retry your command via `jgi-query` and it should work.

You can tell which files are tape archives in the web interface from their legend icons:
![jgi_legend](https://user-images.githubusercontent.com/6827531/38270481-600b30b0-3738-11e8-9dea-00b7d07882c0.png)

There is probably a way to force the query to spin up the archive, but I haven't worked out what it is yet. For reference see this commit: 378f6bd7d5f793068bcd101b0d589ae2c3043dc2

**Comment by liupfskygre** [comment]
Hi Glarue, 
    Thanks. 
Actually I want to download all .faa and .gbk file in this project. I just choose one file to test. For just one or few files it's fine to do in your proposed way, but for all is too much.  I think it is also does not matter if I use jgi-query or the API directly in a loop, right, the same issue will occur?

Otherwise I may contact with our IT to make the globus working. 

Thanks again. 

Cheers,
Pengfei

**Comment by glarue** [comment]
@liupfskygre unfortunately yes, if you are downloading a large number of files (the majority of which are on tape archives) then using `jgi-query` may prove difficult. It might be worth manually checking a random subset of the files you want via the web interface to see if they are mostly in tape archives or not (as I believe it is based on file age, not category).

And yes, I believe you are correct that using the API in a loop won't fix things, since all `jgi-query` is doing is performing queries automatically using the API backend.

If you find a solution outside of globus, please let me know! Closing for now.

**Comment by glarue** [comment]
@liupfskygre my recent commit—moving queries from http to https—may fix the issue you were having and allow you to download tape file archives.

**Comment by glarue** [comment]
@liupfskygre just another small update: there is now an option in the file selection dialog to use a regular expression pattern to match an arbitrarily large number of files, should that prove helpful.
